services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 50051:50051
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    env_file:
      - .env
